name: video_editor_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ffmpeg_kit_flutter_full_gpl: 6.0.3
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.6.1
  gal: ^2.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  video_editor: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/Roboto-Bold.ttf
